language: objective-c

osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

before_install:
    - brew update
    - brew uninstall xctool && brew install --HEAD xctool
install: true
 
xcode_workspace: CF Apps.xcworkspace
xcode_scheme: CF Apps
