language: objective-c

osx_image: xcode7.3
xcode_sdk: iphonesimulator
xcode_workspace: CF Apps.xcworkspace
xcode_scheme: CF Apps

before_install:
  - set -o pipefail

install: true

script:
  - xcodebuild -workspace CF\ Apps.xcworkspace -scheme CF\ Apps -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' build test

after_success:
  - sleep 5
